# Generated by Django 6.1.2 on 2026-10-08 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_movie_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['seat_number']},
        ),
        migrations.AddField(
            model_name='seat',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookings.movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=4),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('movie', 'seat_number'), name='unique_seat_number_per_movie'),
        ),
    ]
