# Generated by Django 6.1.2 on 2026-10-08 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_booking_date_alter_booking_seat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date', '-id']},
        ),
    ]
